### ISSUE TITLE
pnpm

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#104]
## Summary
Migrate from yarn to pNPM

## Todo / ordered steps
- [x] Delete `yarn.lock`
- [x] Reinstall packages by running `pnpm install`
- [x] (? maybe) specify in `engines` section of `package.json` the default package manager as pnpm
- [x] Update `huksy` commands to use pnpm
- [x] Update [README.md](README.md) and [CONTRIBUTING.md](CONTRIBUTING.md) to use pnpm instead of yarn
- [x] Update github actions to use pnpm instead of yarn

## Possible impacts / side effects on existing features
In development it should be pretty easy to know if everything works as planned, we should also test that GitHub actions work properly with cache and everything
