### ISSUE TITLE
Upgrade to Expo SDK 46

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#114]
## Summary
We'll update to the latest expo sdk

## Todo / ordered steps
- [ ] run `npm i -g expo-cli` and `npm i -g eas-cli` to use the latest cli versions
- [x] run `expo upgrade`
- [x] in `eas.json` update the cache key in the base build profile

We don't need to update the GitHub actions because they're already using the latest version

## Possible impacts / side effects on existing features
We'll be able to adopt FlashList #99 

## Additional notes
Release: https://blog.expo.dev/expo-sdk-46-c2a1655f63f7
