### ISSUE TITLE
Refactor: pretyped `useRootStackNavigation` hook

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#12]
## Summary
We should export a pre-typed version of the `useNavigation()` hook provided by `react-native-navigation` to allow for fewer imports and complexities in components

Also, we should expose some types for components that are navigation items like this:
```typescript
type RootStackScreenProps = NativeStackScreenProps<RootStackParamList, T>;
```
Or something like this
## Todo / ordered steps
- [x] Create a `useRootStackNavigation()` in `RootStackNavigation.tsx`  
- [x] Replace `useNavigation()` with this new hook throughout the app
- [x] Create util types for navigation components

## Possible impacts / side effects on existing features
None

## Additional notes
None
