### ISSUE TITLE
Use remote app versioning

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#131]
## Summary
We're going to add support for **Remote versioning** available in the latest update of `eas-cli`

## Todo / ordered steps
- [x] Add the cli option for remote versioning `appVersionSource` (follow this guide in the [docs](https://docs.expo.dev/build-reference/app-versions/#remote-version-source))
- [x] Remove the versions in `app.json` because they will become outdated
- [x] In the settings footer where we show the build number we should find a way to display the remote one, otherwise just remove it
- [x] Update the [Build Workflow](./.github/workflows/eas-build-and-deploy-yml) to tag both the `master` and the `production` branches

```yml
  - name: Config Github Bot for tagging
    if: ${{ github.ref == 'refs/heads/production' && inputs.profile == 'production' }}
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git fetch origin

  - name: Tag on master
    if: ${{ github.ref == 'refs/heads/production' && inputs.profile == 'production' }}
    run: |
      git checkout master
      git tag "v${{steps.version.outputs.prop}}"
      git push origin --tags

  - name: Tag on production
    if: ${{ github.ref == 'refs/heads/production' && inputs.profile == 'production' }}
    run: |
      git checkout production
      git tag "v${{steps.version.outputs.prop}}"
      git push origin --tags
```

## Possible impacts / side effects on existing features
None

## Additional notes
Medium Article: https://blog.expo.dev/eas-build-changelog-43b886b2fa24
