### ISSUE TITLE
Implement EAS metadata

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#132]
## Summary
We're going to hop in the eas metadata beta

## Todo / ordered steps
- [ ] Update to the latest eas cli
- [ ] Update the version inside `eas.json` to `>= 0.54.0`
- [ ] Run `eas metadata:pull` to retrieve the already existing store metadata Infos from the App Store Connect 

## Possible impacts / side effects on existing features
None

## Additional notes
Medium Article: https://blog.expo.dev/eas-build-changelog-43b886b2fa24
Docs: https://docs.expo.dev/eas-metadata/getting-started/
