### ISSUE TITLE
Move Google Services files encoding and decoding to EAS

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#139]
## Summary
EAS now allows for automatic parsing of encoded files, we may want to use that instead of our manual  base64 encoding and decoding for `GoogleServices.json`

## Todo / ordered steps
- [ ] Upload `GoogleServices.json` to eas via `eas secret:create --scope project --name GOOGLE_SERVICES_JSON --type file --value ./path/to/google-services.json`
- [ ] In app.config.json add the config file from the environment variables
```js
  android: {
    googleServicesFile: process.env.GOOGLE_SERVICES_JSON,
    // ...
  },
```
- [ ] Remove the scripts in `package.json`
- [ ] Remove the commands in the build workflows
- [ ] Test that both the local build and the eas build works

## Possible impacts/side effects on existing features
TBD

## Additional notes
Docs: https://docs.expo.dev/build-reference/variables/#how-to-upload-a-secret-file-and
