### ISSUE TITLE
Feat: expo push notifications

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#15]
## Summary
The key feature of the app should be implemented as soon as possible to get to that **MVP** state, the easiest way to implement push notifications seems to be by using the `expo-notifications` library that does everything we need. 

This is handy because it also has a server SDK for node which we can use with firebase functions.
Ref: https://github.com/zaniluca/ping-4-gitlab-functions/issues/2

For testing purposes we can use a curl via postman on cmd:
```bash
curl --location --request POST 'https://exp.host/--/api/v2/push/send' \
--header 'Content-Type: application/json' \
--data-raw '{
  "to": "ExponentPushToken[rqIw6TMNgRZJrOqCXqyanu]",
  "title":"hello",
  "body": "world",
  "badge": 1,
  "sound": "default"
}'
```
Or simply use expo playground: https://expo.dev/notifications
## Todo / ordered steps
- [x] Add `expo-notifications`
- [x] Add notifications handlers for receiving notifications
- [ ] Create utility functions to request permissions, check permission etc..
- [ ] _(Optional, this can be a separate issue when we figure out the firebase connection)_ Upload `ExpoToken` to server
- [x] Add `google-services.json` file
- [x] Add prebuild hook to copy file from secrets:
```
"eas-build-pre-install": "echo $GOOGLE_SERVICES_ANDROID_BASE64 | base64 --decode > ./google-services.json"
```
- [x] follow [this](https://docs.expo.dev/push-notifications/using-fcm/) guide to upload FCM server key to expo

## Possible impacts / side effects on existing features
None

## Additional notes
Pusher video: https://www.youtube.com/watch?v=OLXw0X6dlnM
Expo Docs: https://docs.expo.dev/versions/latest/sdk/notifications/
