### ISSUE TITLE
Feat: firebase for web

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#21]
## Summary
Integrate the web SDK for **firebase**.
This has to be done because rn there are some bugs with the `react-native-firebase` module and to test the server integration we might as well start with the non-native solution provided by firebase that is also compatible with `react-native`.

The idea is that when the app is in a more advanced state we can swap the firebase web module in favor of the `react-native-firebase` one.
## Todo / ordered steps
We'll follow the [expo using firebase guide](https://docs.expo.dev/guides/using-firebase/)
- [x] Run `expo install firebase`
- [x] Create a util file called `firebase.ts` where we will export every native module component, for now, we might probably switch to a more modular approach where we separate every module In its own file with its own functions and stuff.
- [x] Create environment variables for firebase configs and place them in [expo.dev](https://www.expo.dev) console as well
- [x] Test the integration by using the auth module maybe
- [x] Test if `firestore` works correctly because it wasn't in `react-native-firebase`
- [x] If everything seems fine start integrating the feature needed to sign in the user and retrieve notifications
Every enhancement will be added later.

## Additional notes
None
