### ISSUE TITLE
Skeleton loading component

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#24]
## Summary
Implement a Skeleton loading component to display when loading primarily notifications but also anything else if needed.
The component will need to be a basic View, customized to be animated with a skeleton-like opacity fading animation.

## Todo / ordered steps
- [x] Create `Skeleton.tsx` file
- [x] Create something like [this](https://www.youtube.com/watch?v=GEuZQA9CdCM&list=LL&index=1) video
- [x] Allow some view style props (from restyle) to be passed onto the component to allow customizing it
- [x] Create a layout with this new component to replicate the inbox list filled with items and replace it where we now display an activity indicator in `InboxScreen.tsx`
- [x] #37

## Possible impacts / side effects on existing features
None

## Additional notes
Maybe if this turns out to be too sketchy try finding a good and simple library for this.
