### ISSUE TITLE
PoC: Native firebase expo library

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#31]
## Summary
Expo offers a way to integrate native SDK in a managed project with `expo-firebase-core`.
We should test if this is beneficial to us, primarily this would be useful if by using the native SDK we can distinguish between Android and iOS users;

## Todo / ordered steps
- [x] Install `expo-firebase-core`.
- [x] Download `GoogleService-Info.plist` file from firebase console and add it into the project.
- [ ] Upload the **base64 encoded version of the file** to `expo.dev` for `eas` to pick it up.
- [x] Extend the eas-build-pre-install hook to also decode the `GoogleService-Info.plist` file for ios:
```bash
echo $GOOGLE_SERVICES_ANDROID_BASE64 | base64 --decode > ./google-services.json && echo $GOOGLE_SERVICES_IOS_BASE64 | base64 --decode > ./GoogleService-Info.plist
```
- [x] add `ios.googleServicesFile` key to `app.json` pointing to `./GoogleService-Info.plist`
- [x] Follow the guide on expo to replace the firebase config in `firebase.ts`
- [ ] Test that everything works well both on the simulators, on `eas` and when builded for `preview`
- [ ] Remove unused environment vars from Firebase Web SDK

## Possible impacts / side effects on existing features
This will impact almost every firebase flow in the app, a rough testing round will be required
## Additional notes
Using the native Firebase SDK: https://docs.expo.dev/guides/setup-native-firebase/#create-firebase-project
FirebaseCore: https://docs.expo.dev/versions/v44.0.0/sdk/firebase-core/
