### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#43]
## Summary
Implement a dark theme for the whole app.
For now the theme will match the system one

## Todo / ordered steps
- [x] Add `"userInterfaceStyle": "automatic"` to `app.json` and install `expo-system-ui`
- [x] Add the following code to detect if color scheme changed:
```typescript
import { Appearance, useColorScheme } from 'react-native';

function MyComponent() {
  let colorScheme = useColorScheme();

  if (colorScheme === 'dark') {
    // render some dark thing
  } else {
    // render some light thing
  }
}
```
- [x] Update `theme.ts` to include a `darkTheme` which will be an object that overrides the current `theme`, spreading everything except colors that will be modified like this:
```typescript
export const darkTheme = createTheme({
  ...theme,
  colors: {
    ...theme.colors,
    primary: 'insert new color',
  },
});
```
- [x] Add a custom `DarkTheme` for dark mode in `react-native-navigation` check [this](https://reactnavigation.org/docs/themes/) out.
- [x] (Optional) if possible rename `theme` to `lightTheme`
- [x] If not present add background color into every component, allowing us to change the color based on the current theme and not hardcoding it

## Possible impacts / side effects on existing features
Check that the dark style is conforming everywhere

## Additional notes
Expo Docs: https://docs.expo.dev/guides/color-schemes/
React Native Navigation: https://reactnavigation.org/docs/themes/
