### ISSUE TITLE
Password autofill and associated domains

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#49]
## Summary
Add password auto-fill for ios devices, allowing ios users to store passwords in the keychain and get  suggestions when creating a new account and logging in

From what I can tell this will need to have a website, something that at the moment we don't have
## Todo / ordered steps
- [ ] in `app.json` add the associated domain for webcredentials
```javascript
"ios": {
  "bundleIdentifier": "com.zaniluca.ping4gitlab",
  "associatedDomains": ["webcredentials:www.pfg.app"]
},
```
- [ ] Go to apple developers and in the identifiers section find `com.zaniluca.ping4gitlab` bundle and add the **Associated Domains** capabilities
- [ ] Add associated domains file to the website

## Additional notes
Old Gist: https://gist.github.com/amcvitty/42cbe072184fe72485ad17cd7120bb89
How to add associated domains to website: https://developer.apple.com/documentation/xcode/supporting-associated-domains
