### ISSUE TITLE
CI/CD Setup

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#51]
## Summary
Configure a CI/CD environment to build (eventually test) and deploy to the stores all via a push to the `production` branch

## Todo / ordered steps
- [x] Add `eas-build.yml` file which triggers the build in eas
- [x] Add a job in `eas-build` workflow which deploys the latest build for both ios and android
- [x] #70

In the build job at the end commit changes to both production and master branches, they will only include a version bump for both ios and android.
To do this we will need to add the commit action proposed in this issue

- [x] #72
- [x] _(Optional)_ when using the proposed commit action there is also the possibility to specify a `tag`; we might want to use that to mirror the app version in `app.json` and have the current version tracked in Github.
To accomplish this we need to access the content of `app.json` which because it is just a JSON file should be [pretty easy](https://stackoverflow.com/questions/61919141/read-json-file-in-github-actions)
- [ ] _(Optional)_ Related to the previous point if we can read the content from the app.json file we might also use the version in the commit message of the github action

## Possible impacts / side effects on existing features
If we don't commit `app.json` changes after the build, which automatically increments the build number for both platforms, we'll run into inconsistencies because the build number will always be the same.

## Additional notes
Guide: https://techblog.geekyants.com/github-actions-for-automating-builds-for-your-app
How to commit from Github Action: https://github.com/stefanzweifel/git-auto-commit-action
