### ISSUE TITLE
Notification toggle in settings

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#52]
## Summary
We will add a way for users to disable notifications temporarily.
The work will all be done by the server who's not going to send new notifications pushes when the user has explicitly said they don't want to be notified.

This ref: https://github.com/zaniluca/ping-4-gitlab-firebase/issues/16
## Todo / ordered steps
- [x] Add a way for settings row to have a custom content on the right, replacing the icon
- [x] Update types for `UserData` to allow this new prop `hasDisabledNotifications`
- [x] Add a toggle that references the `userData.hasDisabledNotifications` and changes it on click

## Possible impacts / side effects on existing features
None

## Additional notes
None
