### ISSUE TITLE
Work hours settings

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#84]
## Summary
We will add a way for the user to specify the work hours, this will him to choose when he wants to receive notifications like it's done on slack.

## Todo / ordered steps
- [ ] Create a blank screen in a subfolder of screens called settings/`WorkHoursSettingsScreen.tsx`
- [ ] Add the newly created screen in the root navigator with no props
- [ ] Create a new settings section that when pressed sends you to the work hours settings page
> The action will have `chevron-right` icon to the right and `clock` icon to the left

- [ ] Inside `WorkHoursSettingsPage.tsx` add a sectioned list like the one in `SettingsList.tsx` (consider refactoring it to make it reusable)
> This section will be used to create multiple sections in our "form"
- [ ] Add a toggle that says "Use Work Hours" that toggle a boolean in the user's props toggling where or not to use work hours
- [ ] Optionally add a descriptive text below the toggle to let the user what the feature does
- [ ] For time inputs we'll need to distinguish between android and ios because they have a quite different ways to let the user select time.
- [ ] Install `@react-native-community/datetimepicker`
- [ ] TBD

## Possible impacts / side effects on existing features
TBD

## Additional notes
DateTimePicker: https://docs.expo.dev/versions/latest/sdk/date-time-picker/
