### ISSUE TITLE
Allow for account deletion

### ISSUE THREAD

**Issue by zaniluca** [zaniluca/ping-4-gitlab#85]
## Summary
As stated [here](https://developer.apple.com/news/?id=12m75xbj#:~:text=As%20a%20reminder%2C%20apps%20that,5.1.1(v).) by apple app that allows the user to login will have to also allow the complete deletion of the user's account and their related data

We already have a function in the `AuthContext` that allows deleting the user in firebase auth, also on firebase we have an extension in place to automatically delete the user's data from firestore

## Todo / ordered steps
- [x] Add a new settings row called Account with the `chevron-right` icon on the right and on the left `user`
- [x] Create the new screen in screens/settings/`AccountSettingsScreen.tsx`
- [x] Add the newly created screen to the root navigator
- [x] Redirect the user to the new screen when clicking on the Account row in the settings list
- [x] On this screen at the moment we only want to display this action, we'll need to have a sectioned list like the one in `SettingsList.tsx` with only one row which says "Delete account" in a red text
- [x] Once the user presses the button we should display an [alert](https://reactnative.dev/docs/alert) to inform the user that the action is going to delete all of its data permanently
- [x] The alert should have an action to cancel and one to proceed
- [x] Once the user presses proceed we:

1.  Log him out to send it to the landing page
2. Delete his account by calling the `deleteUser()` function in the `AuthContext`

- [ ] **Remember to go in the App/Play Store and update the thing that says "My App allows for user's on-demand data deletion" which as of now its set to false**
## Possible impacts / side effects on existing features
None

## Additional notes
Apple Requirements: https://developer.apple.com/news/?id=12m75xbj#:~:text=As%20a%20reminder%2C%20apps%20that,5.1.1(v).
React Native Alert: 
https://reactnative.dev/docs/alert
